version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-scanner-app
    ports:
      - "8888:8888"
    environment:
      - API_KEY=${API_KEY}
      - API_URL=${API_URL}
      - API_MODEL=${API_MODEL}
      - API_TIMEOUT=${API_TIMEOUT}
      - LOGIN_PASSWORD=${LOGIN_PASSWORD}
      - ANNOUNCEMENT_TEXT=${ANNOUNCEMENT_TEXT}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - stock-scanner-network

networks:
  stock-scanner-network:
    driver: bridge
