version: '3.8'

services:
  stock-analyzer:
    build: .
    ports:
      - "8888:8888"
    environment:
      - API_KEY=${API_KEY}
      - API_URL=${API_URL}
      - API_MODEL=${API_MODEL}
      - API_TIMEOUT=${API_TIMEOUT}
    volumes:
      - .:/app
    restart: unless-stopped
